### ISSUE TITLE
Vulkan: Gamma problem

### ISSUE THREAD

**Issue by divatstaff** [JKSunny/EternalJK#10] opened 2024-01-21 14:21 UTC
Yo

I've been using Vulkan renderer for quite some time in the Tayst version and it works well, unless if i want to take screenshot (windows+shift+s, or just regular print screen) or watch back my shadowplay clips it messes up with the gamma.
Feels like it ignores my value of r_gamma 1.5 and makes the pictures, videos with default value (1) and its super dark.
I tested it, this problem only occurs while using Vulkan with other renderers its fine.

Here's some example, both made with the same gamma yet the Vulkan one makes it really dark.
![image](https://github.com/JKSunny/EternalJK/assets/157291920/3fa2ec22-d104-4ec8-8cdb-77570bd40086)
![image2](https://github.com/JKSunny/EternalJK/assets/157291920/7db7eabc-c9d4-4145-9920-e9108162c3a0)

**Comment by JKSunny** [comment] 2024-01-29 08:24
@divatstaff 

Hey, Thanks for detailed info.

I'll put this on the todo list.

**Comment by JKSunny** [comment] 2024-02-05 16:03
@divatstaff 

What setting do you have for cvar: /r_fbo  
If its 0, can you try setting it to 1 and try again?

**Comment by divatstaff** [comment] 2024-02-05 16:56
![image](https://github.com/JKSunny/EternalJK/assets/157291920/def20821-fc5d-42bc-8c58-f3d9b273b194)
It seems to work for the gamma part, but now i have performance issues seems like my console in a different resolution than my actual game. Really weird

**Comment by JKSunny** [comment] 2024-02-05 18:01
@divatstaff 

Perhaps you accidentaly set the cvar /r_ext_supersample to 1, it doens't have proper console scaling yet.
Use /r_ext_multisample 4 or 8 instead for MSAA

**Comment by JKSunny** [comment] 2024-02-05 19:20
No problem.
Glad the issue is resolved, closing this now

**Closed** 2024-02-05 19:21 UTC
